server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset : UTF-8
      enabled: true
      force: true

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: spring-trello
  datasource:
    url: jdbc:mysql://localhost:3306/trello
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

file:
  upload-dir: C:/uploads

jwt:
  secret:
    key: "fb8e84eb4aab4827836f3199efc34499f4bf6c5374cc404c8851fd5de54de518de53"


